Incremental research
kamayatsu/chat-space pull request #8
Opened 2019-06-16 12:41 UTC by kamayatsu

# Why
グループ作成・編集の際に、チェックボックスではなく、インクリメンタルサーチでユーザの追加・削除をする為

#What
・user#indexにてrespond_toを設定
・index.json.jbuilderファイルの作成
・user.jsファイルの作成
・初回ロード時に、jQueryが実行されるようにする
　（基本的には、リロードしないとjQueryが実行されない）
・検索結果を候補欄として表示
・検索したユーザが既にチャットメンバーに存在している場合、候補欄には表示しない
・検索がヒットしない場合、もしくは検索したユーザが既にチャットメンバーに存在している場合、
　「一致するユーザが見つかりません」というメッセージを表示
・候補欄にて、追加ボタンをクリックするとチャットメンバー欄に候補を移す
・チャットメンバー欄にて、削除ボタンをクリックすると、候補を削除する
・登録する・更新するボタンを押した際にグループが登録・更新されるようにする

2019-06-16 12:43 UTC, kamayatsu commented
https://gyazo.com/0f52e9999965af9a684a8573e0b34731

2019-06-16 12:44 UTC, kamayatsu commented
https://gyazo.com/057e252f2d63e70470ab6d0175945cc1

2019-06-16 12:45 UTC, kamayatsu commented
https://gyazo.com/4d993df9733f573472de8ed319ad1e77

2019-06-16 12:48 UTC, yuki-uchida requested changes

2019-06-16 12:48 UTC, yuki-uchida commented on app/assets/javascripts/users.js
> +        var already_exists = [];
already_existsでは何が存在しているのかわかりづらいですね。
より具体的に、何が存在しているかを変数名にプラスしましょう

2019-06-16 12:48 UTC, yuki-uchida commented on app/assets/javascripts/users.js
> +            var some = already_exists.some(a => a.id === `${user.id}`);
こちらもsomeをより具体的な名前にしましょう

2019-06-16 12:54 UTC, kamayatsu commented on app/assets/javascripts/users.js
> +        var already_exists = [];
already_existsを既存チャットメンバーという意味でchat-membersに変更しました

2019-06-16 12:54 UTC, kamayatsu commented on app/assets/javascripts/users.js
> +            var some = already_exists.some(a => a.id === `${user.id}`);
someをメンバーを含んでいるかのチェックという意味で、member_include_checkに修正しました

2019-06-16 12:54 UTC, kamayatsu commented
２点修正しました。ご確認のほどよろしくお願いいたします。

2019-06-16 12:56 UTC, ghost requested changes

2019-06-16 12:56 UTC, hiroki5123 commented on app/assets/javascripts/users.js
> +            appendErrMsgToHTML('一致するユーザが見つかりません');
引数として渡す必要ないので、メソッドの中で直接文字列展開してください

2019-06-16 12:56 UTC, hiroki5123 commented on app/assets/javascripts/users.js
> +          appendErrMsgToHTML('一致するユーザが見つかりません');
こちらも

2019-06-16 12:59 UTC, kamayatsu commented on app/assets/javascripts/users.js
> +            appendErrMsgToHTML('一致するユーザが見つかりません');
引数として渡さず、直接文字展開しました。

2019-06-16 13:00 UTC, kamayatsu commented on app/assets/javascripts/users.js
> +          appendErrMsgToHTML('一致するユーザが見つかりません');
こちらも上記同様の修正をいたしました

2019-06-16 13:00 UTC, kamayatsu commented
一点修正いたしました。ご確認の程よろしくお願いいたします。

2019-06-16 19:09 UTC, TOMARUMARU commented on app/controllers/users_controller.rb
> +    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%")
ログインしているユーザーが含まれないようにしましょう

2019-06-17 11:41 UTC, kamayatsu commented on app/controllers/users_controller.rb
> +    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%")
ログインしているユーザが含まれないよう修正いたしました

2019-06-17 11:42 UTC, kamayatsu commented
一点修正しました。ご確認の程よろしくお願いいたします。

2019-06-17 11:44 UTC, i-date commented
修正分のpushはしていただけたでしょうか？

2019-06-17 11:44 UTC, kamayatsu commented
すみません、反映できておらず少し遅れましたが、先ほどpushしました。

2019-06-17 11:46 UTC, i-date approved these changes
修正ありがとうございます！LGTMとさせていただきます^^

2019-06-17 11:47 UTC, kamayatsu commented
ご確認・ご指摘ありがとうございます！mergeします。

2019-06-17 11:47 UTC, merged